POST https://coffeebrewer.azurewebsites.net/recipes
Content-Type: application/json

{
    "name": "Oh Menina's V60",
    "description": "Oh Menina's V60 description",
    "coffeeAmount": 15,
    "waterTemperature": 94,
    "methodId": 1,
    "grindSize": 3
}