@id=1

PUT  http://localhost:5002/recipes/{{id}}
Content-Type: application/json

{
    "name": "Hoffmann's V60",
    "description": "Hoffmann's V60 description",
    "coffeeAmount": 15,
    "waterTemperature": 94,
    "methodId": 1,
    "grindSize": 0
}