POST http://localhost:5002/steps
Content-Type: application/json

{
    "name": "Kasuya's V60",
    "description": "Kasuya's V60 description",
    "coffeeAmount": 15,
    "waterTemperature": 94,
    "methodId": 1,
    "grindSize": 0
}