POST https://coffeebrewer.azurewebsites.net/steps
Content-Type: application/json

{
    "order": 2,
    "stepType": 2,
    "title": "Wait",
    "description": "Let it bloom",
    "durationInSeconds": 3,
    "recipeId": 3
}