@id=3

PUT  https://coffeebrewer.azurewebsites.net/steps/{{id}}
Content-Type: application/json

{
    "order": 3,
    "stepType": 1,
    "title": "Pour Water",
    "description": "Pour 40 g of water slowly in a circular motion",
    "durationInSeconds": 7,
    "recipeId": 1,
    "waterAmount": 40
}